"""
Tests for morpheus.core.wake
"""
from datetime import datetime, timezone
from morpheus.core.wake import generate_wake_md
from morpheus.core.models import Source, Claim, ProjectState


def test_generate_wake_md_basic():
    source = Source(
        id="src_001",
        path="README.md",
        kind="markdown",
        sha256="abc123",
        size_bytes=100,
        line_count=10,
        modified_at=datetime.now(timezone.utc)
    )
    
    claim = Claim(
        id="clm_001",
        source_id="src_001",
        line_start=5,
        line_end=5,
        excerpt="TODO: implement feature X",
        category="task",
        created_at=datetime.now(timezone.utc)
    )
    
    state = ProjectState(
        sources=[source],
        claims=[claim],
        evidence=[],
        compiled_at=datetime.now(timezone.utc),
        receipt_id="rcpt_test_001"
    )
    
    wake = generate_wake_md(state, "rcpt_test_001")
    
    assert "# WAKE.md" in wake
    assert "rcpt_test_001" in wake
    assert "### Open Tasks" in wake
    assert "implement feature X" in wake
    assert "Generated by Morpheus" in wake
    assert "morpheus verify --all" in wake
    assert "morpheus verify --provenance" not in wake


def test_generate_wake_md_claims_by_category():
    claims = [
        Claim(id="clm_001", source_id="src_001", line_start=1, line_end=1,
              excerpt="TODO: task 1", category="task", created_at=datetime.now(timezone.utc)),
        Claim(id="clm_002", source_id="src_001", line_start=2, line_end=2,
              excerpt="DECISION: use Python", category="decision", created_at=datetime.now(timezone.utc)),
        Claim(id="clm_003", source_id="src_001", line_start=3, line_end=3,
              excerpt="FIXME: broken thing", category="fixme", created_at=datetime.now(timezone.utc)),
    ]
    
    state = ProjectState(
        sources=[],
        claims=claims,
        evidence=[],
        compiled_at=datetime.now(timezone.utc),
        receipt_id="rcpt_001"
    )
    
    wake = generate_wake_md(state, "rcpt_001")
    
    assert "### Open Tasks" in wake
    assert "### Active Decisions" in wake
    assert "### Fixmes" in wake
    assert "task 1" in wake
    assert "use Python" in wake
    assert "broken thing" in wake


def test_generate_wake_md_orders_known_categories_consistently():
    claims = [
        Claim(id="clm_001", source_id="src_001", line_start=1, line_end=1,
              excerpt="FIXME: repair sync", category="fixme", created_at=datetime.now(timezone.utc)),
        Claim(id="clm_002", source_id="src_001", line_start=2, line_end=2,
              excerpt="NOTE: keep context", category="note", created_at=datetime.now(timezone.utc)),
        Claim(id="clm_003", source_id="src_001", line_start=3, line_end=3,
              excerpt="DECISION: use receipts", category="decision", created_at=datetime.now(timezone.utc)),
        Claim(id="clm_004", source_id="src_001", line_start=4, line_end=4,
              excerpt="TODO: document flow", category="task", created_at=datetime.now(timezone.utc)),
        Claim(id="clm_005", source_id="src_001", line_start=5, line_end=5,
              excerpt="HACK: temporary guard", category="hack", created_at=datetime.now(timezone.utc)),
        Claim(id="clm_006", source_id="src_001", line_start=6, line_end=6,
              excerpt="XXX: investigate edge case", category="xxx", created_at=datetime.now(timezone.utc)),
    ]

    state = ProjectState(
        sources=[],
        claims=claims,
        evidence=[],
        compiled_at=datetime.now(timezone.utc),
        receipt_id="rcpt_order",
    )

    wake = generate_wake_md(state, "rcpt_order")

    headings = [
        "### Active Decisions",
        "### Open Tasks",
        "### Fixmes",
        "### Notes",
        "### Hacks",
        "### XXX",
    ]
    positions = [wake.index(heading) for heading in headings]
    assert positions == sorted(positions)


def test_generate_wake_md_empty_project():
    state = ProjectState(
        sources=[],
        claims=[],
        evidence=[],
        compiled_at=datetime.now(timezone.utc),
        receipt_id="rcpt_empty"
    )
    
    wake = generate_wake_md(state, "rcpt_empty")
    
    assert "# WAKE.md" in wake
    assert "rcpt_empty" in wake
    assert "## Current State" in wake
    assert "## Evidence Summary" in wake


def test_generate_wake_md_only_lists_active_claims_in_current_state():
    claims = [
        Claim(
            id="clm_001",
            source_id="src_001",
            line_start=1,
            line_end=1,
            excerpt="TODO: ship this",
            category="task",
            status="active",
            created_at=datetime.now(timezone.utc),
        ),
        Claim(
            id="clm_002",
            source_id="src_001",
            line_start=2,
            line_end=2,
            excerpt="TODO: obsolete task",
            category="task",
            status="resolved",
            created_at=datetime.now(timezone.utc),
        ),
    ]
    state = ProjectState(
        sources=[],
        claims=claims,
        evidence=[],
        compiled_at=datetime.now(timezone.utc),
        receipt_id="rcpt_active",
    )

    wake = generate_wake_md(state, "rcpt_active")

    assert "TODO: ship this" in wake
    assert "TODO: obsolete task" not in wake
    assert "- 1 active claim from 0 sources" in wake.splitlines()


def test_generate_wake_md_lists_sources_referenced_by_active_claims():
    sources = [
        Source(
            id="src_001",
            path="README.md",
            kind="markdown",
            sha256="abc123",
            size_bytes=100,
            line_count=10,
            modified_at=datetime.now(timezone.utc),
        ),
        Source(
            id="src_002",
            path="docs/archive.md",
            kind="markdown",
            sha256="def456",
            size_bytes=200,
            line_count=20,
            modified_at=datetime.now(timezone.utc),
        ),
    ]
    claims = [
        Claim(
            id="clm_001",
            source_id="src_001",
            line_start=5,
            line_end=5,
            excerpt="TODO: document source references",
            category="task",
            status="active",
            created_at=datetime.now(timezone.utc),
        ),
        Claim(
            id="clm_002",
            source_id="src_002",
            line_start=3,
            line_end=3,
            excerpt="TODO: archived task",
            category="task",
            status="resolved",
            created_at=datetime.now(timezone.utc),
        ),
    ]
    state = ProjectState(
        sources=sources,
        claims=claims,
        evidence=[],
        compiled_at=datetime.now(timezone.utc),
        receipt_id="rcpt_sources",
    )

    wake = generate_wake_md(state, "rcpt_sources")

    assert "## Source References" in wake
    assert "- src_001: `README.md`" in wake.splitlines()
    assert "src_002" not in wake
    assert "docs/archive.md" not in wake


def test_generate_wake_md_pluralizes_evidence_summary_counts():
    source = Source(
        id="src_001",
        path="README.md",
        kind="markdown",
        sha256="abc123",
        size_bytes=100,
        line_count=10,
        modified_at=datetime.now(timezone.utc),
    )
    claims = [
        Claim(
            id="clm_001",
            source_id="src_001",
            line_start=1,
            line_end=1,
            excerpt="TODO: first task",
            category="task",
            created_at=datetime.now(timezone.utc),
        ),
        Claim(
            id="clm_002",
            source_id="src_001",
            line_start=2,
            line_end=2,
            excerpt="TODO: second task",
            category="task",
            created_at=datetime.now(timezone.utc),
        ),
    ]
    state = ProjectState(
        sources=[source],
        claims=claims,
        evidence=[],
        compiled_at=datetime.now(timezone.utc),
        receipt_id="rcpt_plural",
    )

    wake = generate_wake_md(state, "rcpt_plural")

    assert "- 2 active claims from 1 source" in wake.splitlines()


def test_generate_wake_md_renders_multiline_claims_as_single_bullets():
    claim = Claim(
        id="clm_001",
        source_id="src_001",
        line_start=1,
        line_end=2,
        excerpt="DECISION: keep receipts signed\nTODO: document the verification flow",
        category="decision",
        created_at=datetime.now(timezone.utc),
    )
    state = ProjectState(
        sources=[],
        claims=[claim],
        evidence=[],
        compiled_at=datetime.now(timezone.utc),
        receipt_id="rcpt_multiline",
    )

    wake = generate_wake_md(state, "rcpt_multiline")

    assert (
        "- DECISION: keep receipts signed TODO: document the verification flow "
        "*(src:src_001:1)*"
    ) in wake
    assert "\nTODO: document the verification flow" not in wake


def test_generate_wake_md_formats_aware_compiled_time_as_utc_z():
    state = ProjectState(
        sources=[],
        claims=[],
        evidence=[],
        compiled_at=datetime(2026, 5, 13, 12, 0, 0, tzinfo=timezone.utc),
        receipt_id="rcpt_time",
    )

    wake = generate_wake_md(state, "rcpt_time")

    assert "2026-05-13T12:00:00Z" in wake
    assert "+00:00Z" not in wake
