"""
WAKE.md generator.
"""
from datetime import datetime, timezone

from morpheus.core.models import ProjectState


def generate_wake_md(state: ProjectState, receipt_id: str) -> str:
    """Generate WAKE.md from project state."""
    compiled_at = format_utc_timestamp(state.compiled_at)
    lines = [
        "# WAKE.md — Project State",
        "",
        f"**Compiled:** {compiled_at}",
        f"**Receipt:** {receipt_id}",
        "**Morpheus:** v0.1.0",
        "",
        "---",
        "",
        "## Current State",
        "",
    ]

    by_category = {}
    for claim in state.claims:
        cat = claim.category
        by_category.setdefault(cat, []).append(claim)

    category_titles = {
        "decision": "### Active Decisions",
        "task": "### Open Tasks",
        "fixme": "### Fixmes",
        "note": "### Notes",
        "hack": "### Hacks",
    }

    for cat, claims in by_category.items():
        title = category_titles.get(cat, f"### {cat.title()}")
        lines.append(title)
        lines.append("")
        for c in claims:
            lines.append(f"- {c.excerpt} *(src:{c.source_id}:{c.line_start})*")
        lines.append("")

    active_claims = [c for c in state.claims if c.status == "active"]
    lines.extend([
        "## Evidence Summary",
        f"- {len(active_claims)} active claims from {len(state.sources)} sources",
        f"- Compiled: {compiled_at}",
        "",
        "---",
        "",
        "*Generated by Morpheus. Verify with `morpheus verify --all`.*",
    ])

    return "\n".join(lines)


def format_utc_timestamp(value: datetime) -> str:
    """Return an ISO-8601 UTC timestamp with a single trailing Z."""
    if value.tzinfo is None:
        value = value.replace(tzinfo=timezone.utc)
    return value.astimezone(timezone.utc).replace(tzinfo=None).isoformat() + "Z"
