"""
WAKE.md generator.
"""
from datetime import datetime, timezone

from morpheus import __version__ as MORPHEUS_VERSION
from morpheus.core.models import ProjectState


CATEGORY_ORDER = ["decision", "task", "fixme", "note", "hack", "xxx"]
CATEGORY_TITLES = {
    "decision": "### Active Decisions",
    "task": "### Open Tasks",
    "fixme": "### Fixmes",
    "note": "### Notes",
    "hack": "### Hacks",
    "xxx": "### XXX",
}


def generate_wake_md(state: ProjectState, receipt_id: str) -> str:
    """Generate WAKE.md from project state."""
    compiled_at = format_utc_timestamp(state.compiled_at)
    lines = [
        "# WAKE.md — Project State",
        "",
        f"**Compiled:** {compiled_at}",
        f"**Receipt:** {receipt_id}",
        f"**Morpheus:** v{MORPHEUS_VERSION}",
        "",
        "---",
        "",
        "## Current State",
        "",
    ]

    active_claims = [c for c in state.claims if c.status == "active"]

    by_category = {}
    for claim in active_claims:
        cat = claim.category
        by_category.setdefault(cat, []).append(claim)

    for cat in sorted(by_category, key=category_sort_key):
        claims = by_category[cat]
        title = CATEGORY_TITLES.get(cat, f"### {cat.title()}")
        lines.append(title)
        lines.append("")
        for c in claims:
            excerpt = format_claim_excerpt(c.excerpt)
            lines.append(f"- {excerpt} *(src:{c.source_id}:{c.line_start})*")
        lines.append("")

    referenced_source_ids = {claim.source_id for claim in active_claims}
    referenced_sources = [
        source for source in state.sources if source.id in referenced_source_ids
    ]
    if referenced_sources:
        lines.extend(["## Source References", ""])
        for source in referenced_sources:
            lines.append(f"- {source.id}: `{source.path}`")
        lines.append("")

    lines.extend([
        "## Evidence Summary",
        (
            f"- {len(active_claims)} active {pluralize(len(active_claims), 'claim')} "
            f"from {len(state.sources)} {pluralize(len(state.sources), 'source')}"
        ),
        f"- Compiled: {compiled_at}",
        "",
        "---",
        "",
        "*Generated by Morpheus. Verify with `morpheus verify --all`.*",
    ])

    return "\n".join(lines)


def category_sort_key(category: str) -> tuple[int, str]:
    """Sort known WAKE sections first, with unknown categories stable by name."""
    try:
        return (CATEGORY_ORDER.index(category), "")
    except ValueError:
        return (len(CATEGORY_ORDER), category)


def format_claim_excerpt(excerpt: str) -> str:
    """Collapse claim excerpts to one readable Markdown bullet line."""
    return " ".join(excerpt.split())


def pluralize(count: int, singular: str, plural: str | None = None) -> str:
    """Return a singular or plural noun for a count."""
    if count == 1:
        return singular
    return plural or f"{singular}s"


def format_utc_timestamp(value: datetime) -> str:
    """Return an ISO-8601 UTC timestamp with a single trailing Z."""
    if value.tzinfo is None:
        value = value.replace(tzinfo=timezone.utc)
    return value.astimezone(timezone.utc).replace(tzinfo=None).isoformat() + "Z"
